name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install rector
      run: composer global require rector/rector

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy
      run: ~/.composer/vendor/bin/rector process vendor

    - name: Run PHP-Prefixer
      run: php prefix.php

    - name: Delete old prefixed
      run: rm -rf vendor_prefixed

    - name: Create prefixed
      run: mv vendor vendor_prefixed

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Commit artifacts...
        branch: ${{ github.head_ref }}
