name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy
      run: cp composer.json composer.bakup

      # - name: Run PHP-Prefixer
      #   uses: PHP-Prefixer/php-prefixer-build-action@main
      #   with:
      #     personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     project_id: ${{ secrets.PROJECT_ID }}
      #     token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      #  mv -r vendor_prefixed prefixed && \
    - name: Restore
      run: rm -rf prefixed &&
           mkdir prefixed &&
           mkdir prefixed/vendor &&
           mkdir prefixed/vendor_prefixed &&
           cp -r vendor/. prefixed/vendor &&
           rm -rf vendor &&
           mv composer.json prefixed/composer.json &&
           mv composer.bakup composer.json

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Commit artifacts...
        branch: ${{ github.head_ref }}
