name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install rector
      run: composer global require rector/rector

    - name: Delete existing
      run: rm -rf vendor

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Process with Rector
      run: ~/.composer/vendor/bin/rector process vendor

    - name: Fix the composer entries
      run: php prefix.php

    - name: Patch composer
      run: npm install && npm run mapit

    - uses: stefanzweifel/git-auto-commit-action@v4.14.0
      with:
        commit_message: Commit artifacts...
        branch: ${{ github.head_ref }}
